import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

print("--- Start of Extended Classification Pipeline (ABC + Hair Features) ---")

# 1. Load the final DataFrame with features
# Make sure that 'df_with_all_features.csv' has been correctly generated by main_analysis.py
try:
    df_final = pd.read_csv('df_with_all_features.csv')
    print(f"DataFrame 'df_with_all_features.csv' loaded successfully. Rows: {len(df_final)}")
except FileNotFoundError:
    print("Error: 'df_with_all_features.csv' not found. Make sure you have run 'main_analysis.py' first.")
    exit()
except Exception as e:
    print(f"Error while loading the DataFrame: {e}")
    exit()

# 2. Definition and Preparation of Features for the Extended Model
# These are the ABC features + hair features
features_for_extended_model = [
    'rotational_asymmetry_score',
    'compactness_score',
    'mean_color_B', 'mean_color_G', 'mean_color_R',
    'std_color_B', 'std_color_G', 'std_color_R',
    'hair_coverage_pct'
]

# Check if all required columns exist in the DataFrame
missing_features = [f for f in features_for_extended_model if f not in df_final.columns]
if missing_features:
    print(f"Error: The following features for the extended model were not found in the DataFrame: {missing_features}")
    print("Make sure that 'features_extractor.py' and 'main_analysis.py' are generating them correctly.")
    exit()

# Filter the DataFrame by removing rows with NaN in ANY of the features we will use
df_processed = df_final.dropna(subset=features_for_extended_model)
print(f"Rows after removing NaN in ABC + Hair features: {len(df_processed)}")

if df_processed.empty:
    print("No valid data remains after removing NaN. Unable to proceed with classification.")
    exit()

# X: Features (ABC + Hair)
X = df_processed[features_for_extended_model]
# y: Target label (melanoma vs non_melanoma)
y = df_processed['label'].apply(lambda x: 1 if x == 'melanoma' else 0)

print(f"\nClass distribution in the extended dataset (1=melanoma, 0=non_melanoma):\n{y.value_counts()}")

# 3. Split the dataset into Training and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"\nTraining set sizes: X={X_train.shape}, y={y_train.shape}")
print(f"Test set sizes: X={X_test.shape}, y={y_test.shape}")

# 4. Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\nFeatures standardized.")

# 5. Train the Extended Model (Logistic Regression)
model_extended = LogisticRegression(random_state=42, solver='liblinear', class_weight='balanced')
model_extended.fit(X_train_scaled, y_train)

print("\nExtended model (Logistic Regression) trained.")

# 6. Evaluate the Extended Model
y_pred_extended = model_extended.predict(X_test_scaled)
y_prob_extended = model_extended.predict_proba(X_test_scaled)[:, 1] # Probability of the positive class (melanoma)

print("\n--- Extended Model Evaluation Metrics ---")
print(f"Accuracy: {accuracy_score(y_test, y_pred_extended):.4f}")
print(f"Precision (Melanoma): {precision_score(y_test, y_pred_extended, pos_label=1):.4f}")
print(f"Recall (Melanoma): {recall_score(y_test, y_pred_extended, pos_label=1):.4f}")
print(f"F1-Score (Melanoma): {f1_score(y_test, y_pred_extended, pos_label=1):.4f}")
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_prob_extended):.4f}")

# Confusion Matrix
cm_extended = confusion_matrix(y_test, y_pred_extended)
print("\nConfusion Matrix (Extended):")
print(cm_extended)

# Confusion Matrix Visualization
plt.figure(figsize=(6, 5))
sns.heatmap(cm_extended, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Non-Melanoma (0)', 'Melanoma (1)'],
            yticklabels=['Non-Melanoma (0)', 'Melanoma (1)'])
plt.title('Confusion Matrix - Extended Model (ABC + Hair)')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

# ROC Curve
fpr_extended, tpr_extended, thresholds = roc_curve(y_test, y_prob_extended)
plt.figure(figsize=(7, 6))
plt.plot(fpr_extended, tpr_extended, color='darkgreen', lw=2, label=f'Extended ROC Curve (AUC = {roc_auc_score(y_test, y_prob_extended):.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (FPR)')
plt.ylabel('True Positive Rate (TPR)')
plt.title('ROC Curve - Extended Model (ABC + Hair)')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

print("\n--- Extended Classification Pipeline Completed ---")